### ISSUE TITLE
Not clear how to unstage a directory

### ISSUE THREAD

**Issue by v** [Oxen-AI/Oxen#1]
## Reproduction steps

Add a directory to oxen

```
$ mkdir images
$ oxen add images
$ oxen status
On branch main -> d4927984fd596e95

Directories to be committed
  added: images
```

Remove the directory. Oxen still thinks something is modified.
```
$ rm -r images
$ oxen status
On branch main -> d4927984fd596e95

Directories to be committed
  added: images
```

I tried `oxen reset <file>` and that didn't work.

**Comment by gschoeni** [comment]
@v fixed in release v0.2.2 we now have a `--staged` flag on `oxen restore`

Usage 

```
$ oxen restore --staged <pathspec>
```
