### ISSUE TITLE
[Feature] Any chance to provide a windows build release?

### ISSUE THREAD

**Issue by leomeih** [Oxen-AI/Oxen#10]
A lot of assets needs to be preprocessed in windows platform because there're far more tools available.

**Comment by Jasper-Bekkers** [comment]
> Yep we have a pull request with fixes for windows [here](https://github.com/Oxen-AI/Oxen/pull/94), will add a binary to the next release

For it all to work the follow-up is required too

**Comment by gschoeni** [comment]
Windows build is integrated into our CI / release builds now, feel free to try it the binaries [here](https://github.com/Oxen-AI/Oxen/releases)
