### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by luanmuniz** [Oxen-AI/Oxen#11]
I just tried to install it on my macOS using homebrew and when I try to use, i get this error message.

```
$ oxen
-bash: /usr/local/bin/oxen: Bad CPU type in executable
```

My mac is an Intel Core i7 from 2018
Im running Version 13.0.1 (22A400)

Let me know if you need any other information

**Comment by gschoeni** [comment]
We need to add an intel build to our CI, in the meantime you can build and install from source [here](https://github.com/Oxen-AI/Oxen)

**Comment by gschoeni** [comment]
Added x86_64 build to homebrew install, this should fix it!

**Comment by luanmuniz** [comment]
Thanks, confirm that it's working now!
