### ISSUE TITLE
Self-hosting an Oxen endpoint?

### ISSUE THREAD

**Issue by dav-ell** [Oxen-AI/Oxen#48]
This is exactly what I'm looking for as a replacement to dvc for very large datasets (millions of files, TBs of data), but having to upload data to Oxen's cloud is a dealbreaker because I'm locked into AWS. Is it possible to self-host your Oxen backend service so I can still use your tools but upload to my own cloud?

Thanks!

**Comment by dav-ell** [comment]
Apologies, just found the answer: https://github.com/Oxen-AI/oxen-release/blob/main/SelfHosting.md

**Comment by gschoeni** [comment]
Glad you found it! FYI we'll be merging in a major overhaul soon to the core merkle tree data structure that's going to make the millions of files use case even faster, so I might hold off for a week or so to avoid a migration. I'll ping this thread when it's merged.

**Comment by dav-ell** [comment]
Thanks, much appreciated! Will keep a look out.

**Comment by gschoeni** [comment]
Hey @dav-ell, rolled out v0.19.0 which has a lot of performance and stability improvements. Let us know what you think!

**Comment by dav-ell** [comment]
Thanks! Is it possible to back up my data to a S3 bucket yet? I'm about to switch from dvc to this, but the only way I can think of making the switch is to host an EC2 instance with my S3 bucket FUSE-mounted, exposing the EC2 instance with API Gateway, and pointing my oxen client on the machine with my data to the oxen server on the EC2 instance. Would that work? Is there a better way to do it?

**Comment by gschoeni** [comment]
The FUSE-mounted S3 bucket should work, let me know how the performance is when you do it.

We are working on more native S3 support where you can specify a S3 remote in your config similar to DVC. I'll let you know when that's ready as well!

**Comment by jprybylski** [comment]
@gschoeni Just wondering what the current status is on the native S3 support. I see it's still a work in progress, but are we thinking 2025 for that or longer?

**Comment by gschoeni** [comment]
@jprybylski we are hoping to have it by end of June this year. Most of the interfaces are in place so it is mostly implementation and performance testing at this point.

**Comment by dav-ell** [comment]
Fyi https://github.com/Oxen-AI/oxen-release/blob/main/Installation.md does not exist anymore and hasn't existed for about two years at that location. I found it in a commit from 2023: https://github.com/Oxen-AI/oxen-release/blob/13adbbf44c0431b6b99766874dbb1dcfc0dcc097/Installation.md

**Comment by gschoeni** [comment]
Thanks for the heads up @dav-ell we moved the installation to our https://docs.oxen.ai/getting-started/install

Where did you find the https://github.com/Oxen-AI/oxen-release/blob/main/Installation.md link?
